CREATE DATABASE IF NOT EXISTS flows;

CREATE USER IF NOT EXISTS flows_writer IDENTIFIED WITH no_password HOST ANY;
GRANT CREATE TABLE, ALTER TABLE, INSERT, SELECT ON flows.* TO flows_writer;
GRANT SELECT ON INFORMATION_SCHEMA.COLUMNS TO flows_writer;

CREATE USER IF NOT EXISTS grafana_reader IDENTIFIED WITH no_password HOST ANY;
GRANT SELECT ON flows.* TO grafana_reader;
