apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: telemetry
spec:
  ports:
    - name: http
      port: 8123
      protocol: TCP
      targetPort: 8123
    - name: native
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    telemetry.willh.dev/component: clickhouse
  type: ClusterIP
