apiVersion: v1
kind: Service
metadata:
  name: telegraf-ipfix
  namespace: telemetry
spec:
  externalTrafficPolicy: Local
  ports:
    - name: ipfix
      port: 2055
      protocol: UDP
      targetPort: ipfix
  selector:
    app.kubernetes.io/instance: telegraf
    app.kubernetes.io/name: telegraf
  type: LoadBalancer
