apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: 1h
    fluxcd.controlplane.io/reconcileArtifactEvery: 10m
    fluxcd.controlplane.io/reconcileTimeout: 5m
spec:
  distribution:
    version: 2.9.4
    registry: ghcr.io/fluxcd
    artifact: oci://ghcr.io/controlplaneio-fluxcd/flux-operator-manifests
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  cluster:
    type: kubernetes
    size: small
    multitenant: false
    networkPolicy: true
    domain: cluster.local
  sync:
    kind: GitRepository
    url: https://github.com/willhdevs/kind-gitops-flux.git
    ref: refs/heads/main
    path: clusters/local
