apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - stack-kustomization.yaml
  - flux-monitoring-source.yaml
  - flux-monitoring-kustomization.yaml
  - dashboards
